/*
 Generated by typeshare 1.13.4
*/

export type I64 = number;

/** A note of a user. The content is encrypted at rest. */
export interface Note {
	id: string;
	owner_id: string;
	title: string;
	content: string;
	created_at: I64;
	updated_at: I64;
}

/** Response for [CreateNote]. */
export type CreateNoteResponse = Note;

/** Represents an empty json object: `{}` */
export interface NoData {
}

/** Response for [DeleteNote]. */
export type DeleteNoteResponse = NoData;

/** Response for [DeleteUser]. */
export type DeleteUserResponse = NoData;

/** Response for [GetNote]. */
export type GetNoteResponse = Note;

/** An external login linked to a [User]. */
export interface LinkedLogin {
	/** The id of the external login provider. */
	provider_id: string;
	/** The id of the user at the provider. */
	external_id: string;
	/** The avatar the provider sent, if any. */
	avatar_url?: string;
}

/** The workload identity rule a workload [User] belongs to. */
export interface WorkloadLink {
	/** The id of the trusted issuer. */
	issuer_id: string;
	/** The id of the rule within the issuer. */
	rule_id: string;
	/** The subject (`sub`) of the last token exchanged. */
	last_subject: string;
}

/** An app user. Never includes any credentials. */
export interface User {
	id: string;
	username: string;
	/** Disabled users can log in, but can't use the app api. */
	enabled: boolean;
	admin: boolean;
	groups: string[];
	/** Whether the user can log in with a password. */
	has_password: boolean;
	totp_enrolled: boolean;
	passkey_enrolled: boolean;
	external_skip_2fa: boolean;
	linked_logins: LinkedLogin[];
	/** Set for users which belong to a workload identity rule. */
	workload?: WorkloadLink;
	/** The ips the user can log in / call the api from. Empty allows all. */
	cidr_whitelist: string[];
	created_at: I64;
	updated_at: I64;
}

/** Response for [GetUser]. */
export type GetUserResponse = User;

/** The kind of an [ApiKey]: how it authenticates. */
export enum ApiKeyKind {
	/** An api key: `X-API-KEY` / `X-API-SECRET`. */
	ApiKey = "ApiKey",
	/**
	 * A signing key: the request is signed with its private key
	 * (`X-API-PUBLIC-KEY` / `X-API-HOST` / `X-API-TIMESTAMP` /
	 * `X-API-NONCE` / `X-API-SIGNATURE`).
	 */
	SigningKey = "SigningKey",
}

/** An api key or signing key of a user. Never includes the secret. */
export interface ApiKey {
	/** The key (api key) or public key (signing key). */
	key: string;
	kind: ApiKeyKind;
	user_id: string;
	name: string;
	/** Unix timestamp in ms the key stops working at. 0 is never. */
	expires: I64;
	cidr_whitelist: string[];
	created_at: I64;
}

/** Response for [ListApiKeys]. */
export type ListApiKeysResponse = ApiKey[];

/** A [Note] without the content. */
export interface NoteListItem {
	id: string;
	owner_id: string;
	title: string;
	created_at: I64;
	updated_at: I64;
}

/** Response for [ListNotes]. */
export type ListNotesResponse = NoteListItem[];

/** Response for [ListUsers]. */
export type ListUsersResponse = User[];

/** Response for [UpdateCidrWhitelist]. */
export type UpdateCidrWhitelistResponse = User;

/** Response for [UpdateNote]. */
export type UpdateNoteResponse = Note;

/** Response for [UpdateUserAccess]. */
export type UpdateUserAccessResponse = User;

/**
 * Create a note owned by the calling user.
 * Response: [Note].
 */
export interface CreateNote {
	title: string;
	content?: string;
}

/**
 * Delete a note of the calling user.
 * Response: [NoData].
 */
export interface DeleteNote {
	id: string;
}

/**
 * Delete a user and everything they own. Admin only.
 * Response: [NoData].
 */
export interface DeleteUser {
	user_id: string;
}

/**
 * Generate an Ed25519 key pair, eg. to create a signing key with.
 * Response: [GenerateKeyPairResponse].
 */
export interface GenerateKeyPair {
}

/** Response for [GenerateKeyPair]. */
export interface GenerateKeyPairResponse {
	/** The pkcs8 encoded private key. The server doesn't keep it. */
	private_key: string;
	/** The spki encoded public key. */
	public_key: string;
}

/**
 * Get info about the server.
 * Response: [GetCoreInfoResponse].
 */
export interface GetCoreInfo {
}

/** Response for [GetCoreInfo]. */
export interface GetCoreInfoResponse {
	app_name: string;
	/**
	 * The address the app is reached at. Requests with a signing
	 * key are signed for its host.
	 */
	host: string;
}

/**
 * Get a note of the calling user, including its content.
 * Response: [Note].
 */
export interface GetNote {
	id: string;
}

/**
 * Get what the server knows about the request itself.
 * Response: [GetRequestInfoResponse].
 */
export interface GetRequestInfo {
}

/** How the request was authenticated. */
export enum AuthMethod {
	Jwt = "Jwt",
	ApiKey = "ApiKey",
	PublicKey = "PublicKey",
}

/** Response for [GetRequestInfo]. */
export interface GetRequestInfoResponse {
	/** The client ip, as seen by the server. */
	ip: string;
	auth_method: AuthMethod;
	user_id: string;
}

/**
 * Get counts of what is stored. Cached for a few seconds.
 * Response: [GetStatsResponse].
 */
export interface GetStats {
}

/** Response for [GetStats]. */
export interface GetStatsResponse {
	users: I64;
	notes: I64;
	api_keys: I64;
	/** Unix timestamp in ms the counts were taken at. */
	computed_at: I64;
}

/**
 * Get the calling user.
 * Response: [User].
 */
export interface GetUser {
}

/**
 * Get the version of the server.
 * Response: [GetVersionResponse].
 */
export interface GetVersion {
}

/** Response for [GetVersion]. */
export interface GetVersionResponse {
	version: string;
}

/**
 * List the api keys of the calling user.
 * Response: [ListApiKeysResponse].
 */
export interface ListApiKeys {
}

/**
 * List the notes of the calling user.
 * Response: [ListNotesResponse].
 */
export interface ListNotes {
	/** Only notes with a title containing this. */
	query?: string;
}

/**
 * List all users. Admin only.
 * Response: [ListUsersResponse].
 */
export interface ListUsers {
}

/**
 * Decrypt text sealed by the calling user with [SealText].
 * Response: [OpenTextResponse].
 */
export interface OpenText {
	sealed: string;
}

/** Response for [OpenText]. */
export interface OpenTextResponse {
	text: string;
}

/**
 * Encrypt text with the server key, bound to the calling user.
 * Response: [SealTextResponse].
 */
export interface SealText {
	text: string;
}

/** Response for [SealText]. */
export interface SealTextResponse {
	sealed: string;
}

/**
 * Set the ips the calling user can log in / call the api from.
 * Response: [User].
 */
export interface UpdateCidrWhitelist {
	/** CIDR ranges or ips. Empty allows all. */
	cidr_whitelist: string[];
}

/**
 * Update a note of the calling user.
 * Response: [Note].
 */
export interface UpdateNote {
	id: string;
	/** The new title. Unchanged if not given. */
	title?: string;
	/** The new content. Unchanged if not given. */
	content?: string;
}

/**
 * Enable / disable a user, make them admin, or set their groups. Admin only.
 * Response: [User].
 */
export interface UpdateUserAccess {
	user_id: string;
	/** Unchanged if not given. */
	enabled?: boolean;
	/** Unchanged if not given. */
	admin?: boolean;
	/** Unchanged if not given. */
	groups?: string[];
}

/** What an input is validated as by [ValidateString]. */
export enum ValidateStringKind {
	Username = "Username",
	VariableName = "VariableName",
	HttpUrl = "HttpUrl",
	NoteTitle = "NoteTitle",
}

/**
 * Check an input against the validation rules of the server.
 * Response: [ValidateStringResponse].
 */
export interface ValidateString {
	kind: ValidateStringKind;
	input: string;
}

/** Response for [ValidateString]. */
export interface ValidateStringResponse {
	valid: boolean;
	/** Why the input is not valid. */
	error?: string;
}

export type ExecuteRequest = 
	| { type: "GenerateKeyPair", params: GenerateKeyPair }
	| { type: "SealText", params: SealText }
	| { type: "OpenText", params: OpenText }
	| { type: "ValidateString", params: ValidateString };

export type ReadRequest = 
	| { type: "GetVersion", params: GetVersion }
	| { type: "GetCoreInfo", params: GetCoreInfo }
	| { type: "GetRequestInfo", params: GetRequestInfo }
	| { type: "GetStats", params: GetStats }
	| { type: "GetUser", params: GetUser }
	| { type: "ListUsers", params: ListUsers }
	| { type: "ListApiKeys", params: ListApiKeys }
	| { type: "ListNotes", params: ListNotes }
	| { type: "GetNote", params: GetNote };

export type WriteRequest = 
	| { type: "CreateNote", params: CreateNote }
	| { type: "UpdateNote", params: UpdateNote }
	| { type: "DeleteNote", params: DeleteNote }
	| { type: "UpdateCidrWhitelist", params: UpdateCidrWhitelist }
	| { type: "UpdateUserAccess", params: UpdateUserAccess }
	| { type: "DeleteUser", params: DeleteUser };

