/*
 Generated by typeshare 1.13.4
*/

/** JSON containing a jwt authentication token. */
export interface JwtResponse {
	/** A token the user can use to authenticate their requests. */
	jwt: string;
}

/** Response for [CompletePasskeyLogin]. */
export type CompletePasskeyLoginResponse = JwtResponse;

/** Response for [CompleteTotpLogin]. */
export type CompleteTotpLoginResponse = JwtResponse;

/** Response for [ExchangeForJwt]. */
export type ExchangeForJwtResponse = JwtResponse;

/** JSON containing either an authentication token or the required 2fa auth check. */
export type JwtOrTwoFactor = 
	| { type: "Jwt", data: JwtResponse }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

/** The response for [LoginLocalUser] */
export type LoginLocalUserResponse = JwtOrTwoFactor;

export type Passkey = any;

export type PublicKeyCredential = any;

export type RequestChallengeResponse = any;

/** Response for [SignUpLocalUser]. */
export type SignUpLocalUserResponse = JwtResponse;

/**
 * Confirm a single use 2fa pending token + time-dependent user totp code for a jwt.
 * Response: [CompletePasskeyLoginResponse].
 */
export interface CompletePasskeyLogin {
	credential: PublicKeyCredential;
}

/**
 * Confirm a single use 2fa pending token + time-dependent user totp code for a jwt.
 * Response: [CompleteTotpLoginResponse].
 */
export interface CompleteTotpLogin {
	/** The time dependent totp code for user. */
	code: string;
}

/**
 * Retrieve a JWT after completing third party login flows.
 * Response: [ExchangeForJwtResponse].
 */
export interface ExchangeForJwt {
}

/**
 * Non authenticated route to see the available options
 * users have to login, eg. local and external providers.
 * Response: [GetLoginOptionsResponse].
 */
export interface GetLoginOptions {
}

/** The response for [GetLoginOptions]. */
export interface GetLoginOptionsResponse {
	/** Whether local auth is enabled. */
	local: boolean;
	/** Whether user registration (Sign Up) has been disabled */
	registration_disabled: boolean;
}

/**
 * Login as a local user. Will fail if the users credentials don't match
 * any local user.
 */
export interface LoginLocalUser {
	/** The user's username */
	username: string;
	/** The user's password */
	password: string;
}

/**
 * Sign up a new local user account. Will fail if a user with the
 * given username already exists.
 * Response: [SignUpLocalUserResponse].
 */
export interface SignUpLocalUser {
	/** The username for the new user. */
	username: string;
	/**
	 * The password for the new user.
	 * This cannot be retreived later.
	 */
	password: string;
}

export type AuthRequest = 
	| { type: "GetLoginOptions", params: GetLoginOptions }
	| { type: "SignUpLocalUser", params: SignUpLocalUser }
	| { type: "LoginLocalUser", params: LoginLocalUser }
	| { type: "ExchangeForJwt", params: ExchangeForJwt }
	| { type: "CompletePasskeyLogin", params: CompletePasskeyLogin }
	| { type: "CompleteTotpLogin", params: CompleteTotpLogin };

