/*
 Generated by typeshare 1.13.4
*/

/** Represents an empty json object: `{}` */
export interface NoData {
}

export type BeginExternalLoginLinkResponse = NoData;

export type CreationChallengeResponse = any;

/** Response for [BeginPasskeyEnrollment]. */
export type BeginPasskeyEnrollmentResponse = CreationChallengeResponse;

/** JSON containing a jwt authentication token. */
export interface JwtResponse {
	/** A token the user can use to authenticate their requests. */
	jwt: string;
}

/** Response for [CompletePasskeyLogin]. */
export type CompletePasskeyLoginResponse = JwtResponse;

/** Response for [CompleteTotpLogin]. */
export type CompleteTotpLoginResponse = JwtResponse;

/** Response for [CompleteTotpRecoveryLogin]. */
export type CompleteTotpRecoveryLoginResponse = JwtResponse;

/** Response for [ConfirmPasskeyEnrollment]. */
export type ConfirmPasskeyEnrollmentResponse = NoData;

export type U64 = number;

/**
 * Settings to exchange tokens issued by an [ExternalLoginProvider]
 * for an app token at the token endpoint (RFC 8693 Token Exchange).
 * 
 * Only signed ID tokens / JWTs are accepted, which excludes
 * Github. The user the token belongs to must already exist.
 * 
 * ⚠️ Whoever holds a valid token of a user can log in as that user
 * without any interaction, only enable this where it is needed.
 */
export interface TokenExchangeConfig {
	/** Whether tokens of this provider can be exchanged. */
	enabled?: boolean;
	/**
	 * Audiences (`aud`) accepted on exchanged tokens in
	 * addition to the client id of the provider. These are the client
	 * ids of other apps (eg. a CLI) registered at the same provider.
	 * 
	 * ⚠️ Tokens the provider issues to every app listed
	 * here can be used to log in to this app.
	 * 
	 * Note. Users are found by the subject (`sub`) of the token. A
	 * provider using pairwise subject identifiers gives the same user
	 * a different subject per app, so their tokens won't match a user.
	 */
	audiences?: string[];
	/**
	 * Only accept tokens issued (`iat`) at most this many seconds
	 * ago. `0` (default) accepts tokens until they expire.
	 * 
	 * A captured token can be exchanged by anyone until then, and some
	 * providers issue tokens which are valid for hours. Clients are
	 * expected to exchange a token right after receiving it and keep
	 * the app token, so a few minutes is enough.
	 */
	max_token_age_secs?: U64;
}

/** The kind specific configuration of an [ExternalLoginProvider]. */
export type ExternalLoginProviderConfig = 
	| { kind: "Oidc", params: OidcConfig }
	| { kind: "Github", params: NamedOauthConfig }
	| { kind: "Google", params: NamedOauthConfig };

/**
 * An external login provider users can use to log in.
 * Any number of these can be configured, either statically
 * by the app (file / env) or stored by the app and managed over the API.
 */
export interface ExternalLoginProvider {
	/**
	 * The unique id of the provider, stored alongside the external
	 * user id on linked users. The login / callback urls name the
	 * provider by its [slug][ExternalLoginProvider::slug] instead,
	 * which is the id only for providers without a slug.
	 * 
	 * External user ids are only unique per provider,
	 * so an id must never be reused for another provider.
	 */
	id: string;
	/** The display name, eg. shown on the login button. */
	name: string;
	/**
	 * The part of the login / callback urls naming the provider
	 * (`/external/{slug}/callback`), see [ExternalLoginProvider::slug]:
	 * lowercase letters, digits and single hyphens, unique among all
	 * providers, defaulting to the name ([slugify]). Empty on providers
	 * stored before slugs existed, which keep their id in the urls.
	 */
	slug?: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/**
	 * Allow tokens issued by this provider to be
	 * exchanged for an app token (RFC 8693). Disabled by default.
	 */
	token_exchange?: TokenExchangeConfig;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
}

/** An external login provider as listed for admins. */
export interface ExternalLoginProviderListItem {
	/** The provider. The client secret is redacted. */
	provider: ExternalLoginProvider;
	/**
	 * Whether the provider comes from static app configuration
	 * (file / env), in which case it cannot be updated or deleted.
	 */
	read_only: boolean;
	/**
	 * The redirect / callback URI which
	 * must be registered at the provider.
	 */
	redirect_uri: string;
}

export type CreateExternalLoginProviderResponse = ExternalLoginProviderListItem;

/** Where the keys to verify the tokens of a [TrustedIssuer] come from. */
export type TrustedIssuerKeys = 
	/**
	 * OpenID discovery: `{issuer}/.well-known/openid-configuration`
	 * points to the key set (`jwks_uri`). Works for Github Actions,
	 * Gitlab, and clusters which expose their discovery publicly.
	 */
	| { source: "Discovery", params: {
}}
	/** Fetch the key set (JWKS) from this url. */
	| { source: "JwksUri", params: string }
	/**
	 * A fixed key set (JWKS json), for issuers the app server can't
	 * reach or which require authentication, like most Kubernetes
	 * clusters: `kubectl get --raw /openid/v1/jwks`.
	 * Has to be updated when the issuer rotates its keys.
	 */
	| { source: "Static", params: string };

/** A condition on a claim of a workload token. */
export interface WorkloadClaim {
	/**
	 * The name of the claim, eg. `sub` or `repository_id`.
	 * Nested claims are reached with a dotted path,
	 * eg. `kubernetes.io.namespace`.
	 */
	claim: string;
	/**
	 * The value the claim must have. `*` matches any run of
	 * characters, eg. `refs/heads/release/*`. If the claim
	 * is a list, one of its values has to match.
	 */
	pattern: string;
}

/**
 * Accepts the tokens of a [TrustedIssuer] which match all of
 * `claims`, and defines the user those workloads act as.
 * 
 * Each rule has its own user, created on first use by
 * `AuthImpl::get_or_create_workload_user`, with `groups` and
 * `admin` applied on every exchange and whenever the issuer is
 * saved (`AuthImpl::sync_workload_users`). Disabling the rule or
 * its issuer disables the user, which refuses the app tokens it
 * was already issued; enabling it again brings the same user back.
 * Narrowing `claims` only affects new exchanges.
 */
export interface WorkloadRule {
	/**
	 * The unique id of the rule, which identifies its user.
	 * Generated by the server for rules managed over the API.
	 * 
	 * ⚠️ Rules of static issuers must be given one (`a-z A-Z 0-9 - _`),
	 * unique within the issuer. Rules sharing an id would share a user,
	 * so tokens matching such a rule are refused.
	 */
	id?: string;
	/** The display name, used to name the user. */
	name: string;
	enabled?: boolean;
	/**
	 * The conditions a token has to meet. All of them have to
	 * match, and at least one is required.
	 * 
	 * ⚠️ Prefer claims which can't be changed or reused over names, eg.
	 * Github's `repository_id` / `repository_owner_id` over `repository`,
	 * and keep wildcards narrow: `repo:my-org/*` trusts every
	 * repository of the org, including ones created later.
	 */
	claims?: WorkloadClaim[];
	/** The app groups of the user, which the app gives meaning to. */
	groups?: string[];
	/** Whether the user is an admin. */
	admin?: boolean;
	/**
	 * How long the issued app token is valid for, in seconds.
	 * `0` (default) and anything longer use the app default.
	 * Workloads should get short lived tokens, eg. `900`.
	 */
	token_ttl_secs?: U64;
}

/**
 * A token issuer trusted for workload identity: machines (CI jobs,
 * Kubernetes service accounts, ...) exchange the token their platform
 * issues them for an app token at the token endpoint (RFC 8693),
 * so they don't need a long lived api key.
 * 
 * Unlike an [ExternalLoginProvider] nobody logs in here.
 * The issuer only has to publish the keys it signs tokens with,
 * and [WorkloadRule]s decide which tokens are accepted.
 */
export interface TrustedIssuer {
	/** The unique id of the issuer. */
	id: string;
	/** The display name. */
	name: string;
	/** Whether tokens of this issuer are accepted. */
	enabled?: boolean;
	/**
	 * The issuer (`iss`) of the tokens, eg.
	 * `https://token.actions.githubusercontent.com`
	 * or the issuer url of a Kubernetes cluster.
	 */
	issuer: string;
	/** Where the keys to verify tokens come from. */
	keys?: TrustedIssuerKeys;
	/**
	 * The audiences (`aud`) accepted on tokens. At least one is required.
	 * 
	 * ⚠️ Use an audience specific to this app, eg. its url, which the
	 * workload requests its token for. The default audience of a
	 * platform is shared with every other service trusting that
	 * platform, and any of them could replay the tokens they receive.
	 */
	audiences?: string[];
	/**
	 * Only accept tokens issued (`iat`) at most this many seconds ago.
	 * `0` (default) accepts tokens until they expire.
	 */
	max_token_age_secs?: U64;
	/**
	 * Which tokens of the issuer are accepted, and who they act as.
	 * The first enabled rule matching a token decides.
	 */
	rules?: WorkloadRule[];
}

/** A trusted issuer as listed for admins. */
export interface TrustedIssuerListItem {
	issuer: TrustedIssuer;
	/**
	 * Whether the issuer comes from static app configuration
	 * (file / env), in which case it cannot be updated or deleted.
	 */
	read_only: boolean;
}

export type CreateTrustedIssuerResponse = TrustedIssuerListItem;

/** Response for [DeleteApiKey]. */
export type DeleteApiKeyResponse = NoData;

export type DeleteExternalLoginProviderResponse = NoData;

/** Response for [DeleteSigningKey]. */
export type DeleteSigningKeyResponse = NoData;

export type DeleteTrustedIssuerResponse = NoData;

/** JSON containing either an authentication token or the required 2fa auth check. */
export type JwtOrTwoFactor = 
	| { type: "Jwt", data: JwtResponse }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

/** The response for [ExchangeExternalForJwt] */
export type ExchangeExternalForJwtResponse = JwtOrTwoFactor;

/** Response for [ExchangeForJwt]. */
export type ExchangeForJwtResponse = JwtResponse;

export type JsonValue = any;

export type ListExternalLoginProvidersResponse = ExternalLoginProviderListItem[];

export type ListTrustedIssuersResponse = TrustedIssuerListItem[];

/** The response for [LoginLocalUser] */
export type LoginLocalUserResponse = JwtOrTwoFactor;

export type Passkey = any;

export type PublicKeyCredential = any;

export type RegisterPublicKeyCredential = any;

export type RequestChallengeResponse = any;

/** Response for [SignUpLocalUser]. */
export type SignUpLocalUserResponse = JwtResponse;

/** Response for [UnenrollPasskey]. */
export type UnenrollPasskeyResponse = NoData;

/** Response for [UnenrollTotp]. */
export type UnenrollTotpResponse = NoData;

export type UnlinkExternalLoginResponse = NoData;

export type UnlinkLocalLoginResponse = NoData;

export type UpdateExternalLoginProviderResponse = ExternalLoginProviderListItem;

export type UpdateExternalSkip2faResponse = NoData;

export type UpdatePasswordResponse = NoData;

export type UpdateTrustedIssuerResponse = TrustedIssuerListItem;

export type UpdateUsernameResponse = NoData;

/**
 * Begin linking flow for an external login. Response: [NoData].
 * 
 * First call this method when authenticated, then redirect the
 * user to `/external/{slug}/link` relative to the auth api path
 * (eg. `/auth/external/{slug}/link`), using the provider `slug`
 * from [GetLoginOptions][crate::api::login::GetLoginOptions]
 * (see [LoginOptionsProvider][crate::api::login::LoginOptionsProvider]).
 * The slug is not the provider id.
 * 
 * The response sets a new session cookie (the session id changes),
 * and the redirect to `/link` must carry it: only the session which
 * began the link can use it, for 10 minutes. Browsers do this when
 * the request is sent with credentials.
 */
export interface BeginExternalLoginLink {
}

/**
 * Begins enrollment flow for Passkey 2FA.
 * Response: [BeginPasskeyEnrollmentResponse]
 */
export interface BeginPasskeyEnrollment {
}

/**
 * Starts enrollment flow for TOTP 2FA auth support.
 * Response: [BeginTotpEnrollmentResponse]
 * 
 * This generates an otpauth URI for the user. User must confirm
 * by providing a valid 6 digit code for the URI to [ConfirmTotpEnrollment].
 */
export interface BeginTotpEnrollment {
}

/** Response for [BeginTotpEnrollment]. */
export interface BeginTotpEnrollmentResponse {
	/** TOTP enrollment URI for manual addition to password manager. */
	uri: string;
	/** Base64 encoded PNG embeddable in HTML to display uri QR code. */
	png: string;
}

/**
 * Complete login using passkey as second factor.
 * Response: [CompletePasskeyLoginResponse].
 */
export interface CompletePasskeyLogin {
	credential: PublicKeyCredential;
}

/**
 * Complete login using TOTP code as second factor.
 * Response: [CompleteTotpLoginResponse].
 */
export interface CompleteTotpLogin {
	/** The time dependent totp code for user. */
	code: string;
}

/**
 * Complete login using a TOTP recovery code as second factor.
 * Each recovery code can only be used once.
 * Response: [CompleteTotpRecoveryLoginResponse].
 */
export interface CompleteTotpRecoveryLogin {
	/** One of the recovery codes issued at TOTP enrollment. */
	code: string;
}

/**
 * Confirm enrollment flow for Passkey 2FA.
 * Response: [NoData]
 */
export interface ConfirmPasskeyEnrollment {
	credential: RegisterPublicKeyCredential;
}

/**
 * Confirm enrollment flow for TOTP 2FA auth support
 * Response: [ConfirmTotpEnrollmentResponse]
 */
export interface ConfirmTotpEnrollment {
	code: string;
}

/** Response for [ConfirmTotpEnrollment]. */
export interface ConfirmTotpEnrollmentResponse {
	recovery_codes: string[];
}

/**
 * Create an API key for the calling user.
 * Response: [CreateApiKeyResponse].
 */
export interface CreateApiKey {
	/** The name for the api key. */
	name: string;
	/**
	 * A unix timestamp in millseconds specifying api key expire time.
	 * Default is 0, which means no expiry.
	 */
	expires?: U64;
	/**
	 * Whitelist of CIDR ranges (eg `10.0.0.0/8`) or ip addresses
	 * from which requests using this api key are accepted.
	 * Empty (the default) means all ips are allowed.
	 */
	cidr_whitelist?: string[];
}

/** Response for [CreateApiKey]. */
export interface CreateApiKeyResponse {
	/** X-API-KEY */
	key: string;
	/**
	 * X-API-SECRET
	 * 
	 * Note.
	 * There is no way to get the secret again after it is distributed in this response
	 */
	secret: string;
}

/**
 * Create an external login provider. Admin only.
 * The provider id is generated by the server, the slug
 * (the part of its urls naming it) defaults to the name.
 * Response: [ExternalLoginProviderListItem].
 */
export interface CreateExternalLoginProvider {
	/** The display name, eg. shown on the login button. */
	name: string;
	/**
	 * The slug naming the provider in its login / callback urls
	 * (`/external/{slug}/callback`): lowercase letters, digits and
	 * single hyphens, unique among all providers. Empty: made from
	 * the name.
	 */
	slug?: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/**
	 * Allow tokens issued by this provider to be
	 * exchanged for an app token (RFC 8693).
	 */
	token_exchange?: TokenExchangeConfig;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
}

/**
 * Create a signing key for the calling user: a key pair whose
 * public key the server stores, and whose private key signs the
 * requests (see [crate::signature]).
 * Response: [CreateSigningKeyResponse].
 */
export interface CreateSigningKey {
	/** The name for the signing key. */
	name: string;
	/**
	 * A unix timestamp in millseconds specifying signing key expire
	 * time. Default is 0, which means no expiry.
	 */
	expires?: U64;
	/**
	 * Whitelist of CIDR ranges (eg `10.0.0.0/8`) or ip addresses
	 * from which requests signed with this key are accepted.
	 * Empty (the default) means all ips are allowed.
	 */
	cidr_whitelist?: string[];
	/**
	 * Optionally provide a pre-existing public key: an Ed25519
	 * key (spki, base64 or pem). Otherwise, a private key will be
	 * generated and returned in the response
	 */
	public_key?: string;
}

/** Response for [CreateSigningKey]. */
export interface CreateSigningKeyResponse {
	/**
	 * Used to sign requests for authentication
	 * without transmitting the key itself: an Ed25519
	 * key (pkcs8, base64).
	 * 
	 * The server will store the associated public key.
	 * 
	 * If user provides a pre-existing public key,
	 * this field will be null.
	 */
	private_key?: string;
}

/**
 * Create a trusted issuer. Admin only.
 * The ids of the issuer and its rules are generated by the server.
 * Response: [TrustedIssuerListItem].
 */
export interface CreateTrustedIssuer {
	/** The issuer to create. `id` and the rule ids are ignored. */
	issuer: TrustedIssuer;
}

/**
 * Delete an API key for the calling user.
 * Response: [NoData].
 */
export interface DeleteApiKey {
	/** The key which the user intends to delete. */
	key: string;
}

/**
 * Delete an external login provider. Admin only.
 * Users can no longer log in with the provider,
 * and their links to it are removed by the app.
 * Response: [NoData].
 */
export interface DeleteExternalLoginProvider {
	/** The id of the provider to delete. */
	id: string;
}

/**
 * Delete a signing key for the calling user.
 * Response: [NoData].
 */
export interface DeleteSigningKey {
	/** The public key of the signing key to delete. */
	public_key: string;
}

/**
 * Delete a trusted issuer. Admin only.
 * Its workloads can no longer get app tokens,
 * and the users of its rules are removed by the app.
 * Response: [NoData].
 */
export interface DeleteTrustedIssuer {
	/** The id of the issuer to delete. */
	id: string;
}

/**
 * Exchange a token issued by an external login provider for a JWT,
 * without sending the user through the browser.
 * Response: [ExchangeExternalForJwtResponse].
 * 
 * This is the token exchange of the `/token` endpoint (RFC 8693) as
 * part of the login api, with the same rules: the provider must have
 * token exchange enabled, the token must be signed by the provider
 * (ID token / JWT) for an accepted audience, and the user must
 * already exist.
 * 
 * Unlike `/token`, users requiring a second factor for external logins
 * can continue with [CompleteTotpLogin] / [CompletePasskeyLogin].
 * This uses the session, so the client has to keep cookies
 * between the requests.
 */
export interface ExchangeExternalForJwt {
	/** The token issued by the external login provider. */
	token: string;
}

/**
 * Retrieve a JWT after completing third party login flows.
 * Response: [ExchangeForJwtResponse].
 */
export interface ExchangeForJwt {
}

/**
 * Get the available options to login, eg. local and external providers.
 * Response: [GetLoginOptionsResponse].
 */
export interface GetLoginOptions {
}

/** The kind of an external login provider. */
export enum ExternalLoginKind {
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

/**
 * An enabled external login provider to show on the login page.
 * 
 * Login is started by redirecting the user to `/external/{slug}/login`
 * relative to the auth api path, linking with `/external/{slug}/link`.
 */
export interface LoginOptionsProvider {
	/** The provider id, which its links to users carry. */
	id: string;
	/** The slug naming the provider in the login / link urls. */
	slug: string;
	/** The display name of the provider */
	name: string;
	/** The kind of provider, eg. to choose an icon. */
	kind: ExternalLoginKind;
	/** Whether new user registration is disabled for this provider */
	registration_disabled: boolean;
}

/** The response for [GetLoginOptions]. */
export interface GetLoginOptionsResponse {
	/** Whether Local login is enabled. */
	local: boolean;
	/** Whether local user registration (Sign Up) has been disabled */
	registration_disabled: boolean;
	/** The enabled external login providers. */
	providers: LoginOptionsProvider[];
	/**
	 * The slug of the provider the login page should auto-redirect to
	 * instead of showing the login page, if any.
	 * This is the first enabled OIDC provider with `auto_redirect`.
	 */
	auto_redirect?: string;
}

/**
 * Get the calling user's ID.
 * Response: [GetUserIdResponse].
 */
export interface GetUserId {
}

export interface GetUserIdResponse {
	id: string;
}

/**
 * List all configured external login providers,
 * including disabled ones. Admin only.
 * Response: [ListExternalLoginProvidersResponse].
 */
export interface ListExternalLoginProviders {
}

/**
 * List the token issuers trusted for workload identity,
 * including disabled ones. Admin only.
 * Response: [ListTrustedIssuersResponse].
 */
export interface ListTrustedIssuers {
}

/** Login as a local user. */
export interface LoginLocalUser {
	/** The user's username */
	username: string;
	/** The user's password */
	password: string;
}

/**
 * Configuration for a named Oauth2 provider,
 * like Github or Google.
 */
export interface NamedOauthConfig {
	/** Whether this login provider is enabled. */
	enabled?: boolean;
	/**
	 * The Oauth client id.
	 * 
	 * Alias: 'id'
	 */
	client_id?: string;
	/**
	 * The Oauth client secret.
	 * 
	 * Alias: 'secret'
	 */
	client_secret?: string;
}

/** Configuration for OIDC provider */
export interface OidcConfig {
	/** Enable login with configured OIDC provider. */
	enabled?: boolean;
	/**
	 * Configure OIDC provider address for
	 * communcation directly with the app server.
	 * 
	 * Note. Needs to be reachable from the app server.
	 * 
	 * `https://accounts.example.internal/application/o/appname`
	 */
	provider?: string;
	/**
	 * Configure OIDC user redirect host.
	 * 
	 * This is the host address users are redirected to in their browser,
	 * and may be different from the `provider` host.
	 * DO NOT include the `path` part, this must be inferred from the above provider path.
	 * If not provided, the host will be the same as `oidc_provider`.
	 * Eg. `https://accounts.example.external`
	 */
	redirect_host?: string;
	/**
	 * Set OIDC client id
	 * 
	 * Alias: 'id'
	 */
	client_id?: string;
	/**
	 * Set OIDC client secret
	 * 
	 * Alias: 'secret'
	 */
	client_secret?: string;
	/**
	 * Use the full email for usernames.
	 * Otherwise, the @address will be stripped,
	 * making usernames more concise.
	 */
	use_full_email?: boolean;
	/**
	 * Your OIDC provider may set additional audiences other than `client_id`,
	 * they must be added here to make claims verification work.
	 */
	additional_audiences?: string[];
	/**
	 * Automatically redirect unauthenticated users to the OIDC provider
	 * instead of showing the login page.
	 */
	auto_redirect?: boolean;
	/**
	 * Additional scopes to request from the provider,
	 * on top of `openid`, `profile` and `email`.
	 * 
	 * The `groups` scope is requested automatically when the
	 * `groups` claim is used and the provider advertises the scope
	 * (`scopes_supported`). Other scopes needed for the groups
	 * claim, eg. `roles`, must be added here.
	 */
	additional_scopes?: string[];
	/**
	 * The claim containing the groups the user belongs to, eg. `groups`.
	 * Nested claims can be reached with a dotted path,
	 * eg. `realm_access.roles`.
	 * 
	 * Group extraction is disabled if this is empty (default),
	 * unless `allowed_groups` or `admin_groups` are set,
	 * in which case it falls back to `groups`.
	 */
	groups_claim?: string;
	/**
	 * Only allow OIDC login, signup and account linking for
	 * users in at least one of these groups, or in `admin_groups`.
	 * Empty allows all users (default).
	 * 
	 * If the provider does not send any group information
	 * for the user, they are rejected.
	 */
	allowed_groups?: string[];
	/**
	 * Users in at least one of these groups are
	 * reported to the app as admins on OIDC login / signup.
	 * This can be used to onboard new admins through the provider.
	 */
	admin_groups?: string[];
}

/**
 * Sign up a new local user account.
 * Response: [SignUpLocalUserResponse].
 */
export interface SignUpLocalUser {
	/** The username for the new user. */
	username: string;
	/**
	 * The password for the new user.
	 * This cannot be retreived later.
	 */
	password: string;
}

/** A failed token exchange (RFC 6749 section 5.2). */
export interface TokenExchangeError {
	/**
	 * The OAuth error code, and the http status it comes with:
	 * - `invalid_request` (`400`): The request is malformed or uses unsupported parameters.
	 * - `unsupported_grant_type` (`400`): `grant_type` is not token exchange.
	 * - `invalid_grant` (`400`): The subject token was rejected.
	 * - `temporarily_unavailable`: Retry later. Either `429`, too many
	 * failed requests, or `503`, a login provider or trusted issuer of
	 * the token's issuer can't be loaded right now (eg. its keys can't
	 * be fetched). With several of them sharing the issuer, a token the
	 * others rejected is `503` rather than `invalid_grant` while one is
	 * unavailable, as that one might have accepted it.
	 * - `server_error` (`500`)
	 */
	error: string;
	/** Human readable details. */
	error_description?: string;
}

/**
 * The form parameters of a token exchange request (RFC 8693 section 2.1).
 * `resource`, `audience` and `scope` are accepted but have no effect.
 */
export interface TokenExchangeRequest {
	/** Must be [GRANT_TYPE_TOKEN_EXCHANGE]. */
	grant_type: string;
	/** The token issued by the external login provider. */
	subject_token: string;
	/** [TOKEN_TYPE_ID_TOKEN] or [TOKEN_TYPE_JWT]. */
	subject_token_type: string;
	/** Optional. [TOKEN_TYPE_ACCESS_TOKEN] (default) or [TOKEN_TYPE_JWT]. */
	requested_token_type?: string;
	/** Not supported (delegation), requests including it are rejected. */
	actor_token?: string;
	/** Not supported (delegation). */
	actor_token_type?: string;
}

/** A successful token exchange (RFC 8693 section 2.2.1). */
export interface TokenExchangeResponse {
	/** The app token (JWT), sent as `Authorization: Bearer <token>`. */
	access_token: string;
	/** The `requested_token_type`, or [TOKEN_TYPE_ACCESS_TOKEN]. */
	issued_token_type: string;
	/** Always `Bearer`. */
	token_type: string;
	/** Seconds until the app token expires. */
	expires_in: U64;
}

/**
 * Unenrolls user in Passkey 2FA.
 * Response: [NoData]
 */
export interface UnenrollPasskey {
}

/**
 * Unenrolls user in TOTP 2FA.
 * Response: [UnenrollTotpResponse]
 */
export interface UnenrollTotp {
}

/**
 * Unlink an external login provider from the calling user.
 * Response: [NoData].
 */
export interface UnlinkExternalLogin {
	/** The id of the provider to unlink. */
	provider_id: string;
}

/**
 * Remove the password of the calling user,
 * disabling local login. Response: [NoData].
 */
export interface UnlinkLocalLogin {
}

/**
 * Update an external login provider, replacing its
 * name and configuration. Admin only.
 * Response: [ExternalLoginProviderListItem].
 * 
 * - The kind of the provider cannot be changed.
 * - If the client secret is empty or the redacted value from
 * [ListExternalLoginProviders], the existing secret is kept.
 * Pass `clear_client_secret` to remove it instead.
 * - An empty slug keeps the existing one. Changing it changes the
 * redirect URI registered at the provider.
 * - ⚠️ Users stay linked to the provider by its id and their user id
 * (subject) at the provider. Pointing an OIDC provider at another
 * identity provider (issuer) lets that one's users log in to the
 * accounts linked with the same subject. Create a new provider
 * instead, unless the same identity provider only moved.
 */
export interface UpdateExternalLoginProvider {
	/** The id of the provider to update. */
	id: string;
	/** The display name, eg. shown on the login button. */
	name: string;
	/**
	 * The slug naming the provider in its login / callback urls.
	 * Empty keeps the existing one.
	 */
	slug?: string;
	/** Disable new user registration using this provider. */
	registration_disabled?: boolean;
	/**
	 * Allow tokens issued by this provider to be
	 * exchanged for an app token (RFC 8693).
	 */
	token_exchange?: TokenExchangeConfig;
	/** The kind specific provider configuration. */
	config: ExternalLoginProviderConfig;
	/**
	 * Remove the stored client secret, eg. to switch an OIDC
	 * provider to a public client using PKCE. An empty client
	 * secret on its own keeps the stored secret.
	 * 
	 * Cannot be combined with a new client secret.
	 */
	clear_client_secret?: boolean;
}

/**
 * Update whether the calling user skips 2fa when using external login method.
 * Response: [NoData].
 */
export interface UpdateExternalSkip2fa {
	/** Whether user skips 2fa when using external login method. */
	external_skip_2fa: boolean;
}

/**
 * Update the calling user's password.
 * Response: [NoData].
 */
export interface UpdatePassword {
	password: string;
}

/**
 * Replace the trusted issuer with the same `id`. Admin only.
 * Response: [TrustedIssuerListItem].
 * 
 * Rules keep their user as long as they keep their id.
 * Rules with an empty or unknown id are new rules,
 * and get an id generated by the server.
 */
export interface UpdateTrustedIssuer {
	issuer: TrustedIssuer;
}

/**
 * Update the calling user's username.
 * Response: [NoData].
 */
export interface UpdateUsername {
	username: string;
}

export type LoginRequest = 
	| { type: "GetLoginOptions", params: GetLoginOptions }
	| { type: "ExchangeForJwt", params: ExchangeForJwt }
	| { type: "ExchangeExternalForJwt", params: ExchangeExternalForJwt }
	| { type: "SignUpLocalUser", params: SignUpLocalUser }
	| { type: "LoginLocalUser", params: LoginLocalUser }
	| { type: "CompletePasskeyLogin", params: CompletePasskeyLogin }
	| { type: "CompleteTotpLogin", params: CompleteTotpLogin }
	| { type: "CompleteTotpRecoveryLogin", params: CompleteTotpRecoveryLogin };

export type ManageRequest = 
	| { type: "GetUserId", params: GetUserId }
	| { type: "UpdateUsername", params: UpdateUsername }
	| { type: "UpdatePassword", params: UpdatePassword }
	| { type: "BeginExternalLoginLink", params: BeginExternalLoginLink }
	| { type: "UnlinkLocalLogin", params: UnlinkLocalLogin }
	| { type: "UnlinkExternalLogin", params: UnlinkExternalLogin }
	| { type: "ListExternalLoginProviders", params: ListExternalLoginProviders }
	| { type: "CreateExternalLoginProvider", params: CreateExternalLoginProvider }
	| { type: "UpdateExternalLoginProvider", params: UpdateExternalLoginProvider }
	| { type: "DeleteExternalLoginProvider", params: DeleteExternalLoginProvider }
	| { type: "ListTrustedIssuers", params: ListTrustedIssuers }
	| { type: "CreateTrustedIssuer", params: CreateTrustedIssuer }
	| { type: "UpdateTrustedIssuer", params: UpdateTrustedIssuer }
	| { type: "DeleteTrustedIssuer", params: DeleteTrustedIssuer }
	| { type: "BeginPasskeyEnrollment", params: BeginPasskeyEnrollment }
	| { type: "ConfirmPasskeyEnrollment", params: ConfirmPasskeyEnrollment }
	| { type: "UnenrollPasskey", params: UnenrollPasskey }
	| { type: "BeginTotpEnrollment", params: BeginTotpEnrollment }
	| { type: "ConfirmTotpEnrollment", params: ConfirmTotpEnrollment }
	| { type: "UnenrollTotp", params: UnenrollTotp }
	| { type: "UpdateExternalSkip2fa", params: UpdateExternalSkip2fa }
	| { type: "CreateApiKey", params: CreateApiKey }
	| { type: "DeleteApiKey", params: DeleteApiKey }
	| { type: "CreateSigningKey", params: CreateSigningKey }
	| { type: "DeleteSigningKey", params: DeleteSigningKey };

/** JSON containing either an authentication token or the required 2fa auth check. */
export type UserIdOrTwoFactor = 
	| { type: "UserId", data: string }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

