/*
 Generated by typeshare 1.13.4
*/

/** Represents an empty json object: `{}` */
export interface NoData {
}

export type BeginExternalLoginLinkResponse = NoData;

export type CreationChallengeResponse = any;

/** Response for [BeginPasskeyEnrollment]. */
export type BeginPasskeyEnrollmentResponse = CreationChallengeResponse;

/** JSON containing a jwt authentication token. */
export interface JwtResponse {
	/** A token the user can use to authenticate their requests. */
	jwt: string;
}

/** Response for [CompletePasskeyLogin]. */
export type CompletePasskeyLoginResponse = JwtResponse;

/** Response for [CompleteTotpLogin]. */
export type CompleteTotpLoginResponse = JwtResponse;

/** Response for [ConfirmPasskeyEnrollment]. */
export type ConfirmPasskeyEnrollmentResponse = NoData;

/** Response for [ExchangeForJwt]. */
export type ExchangeForJwtResponse = JwtResponse;

/** JSON containing either an authentication token or the required 2fa auth check. */
export type JwtOrTwoFactor = 
	| { type: "Jwt", data: JwtResponse }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

/** The response for [LoginLocalUser] */
export type LoginLocalUserResponse = JwtOrTwoFactor;

export type Passkey = any;

export type PublicKeyCredential = any;

export type RegisterPublicKeyCredential = any;

export type RequestChallengeResponse = any;

/** Response for [SignUpLocalUser]. */
export type SignUpLocalUserResponse = JwtResponse;

/** Response for [UnenrollPasskey]. */
export type UnenrollPasskeyResponse = NoData;

/** Response for [UnenrollTotp]. */
export type UnenrollTotpResponse = NoData;

export type UnlinkLoginResponse = NoData;

export type UpdatePasswordResponse = NoData;

export type UpdateUsernameResponse = NoData;

/**
 * Begin linking flow for an external login. Response: [NoData].
 * 
 * First call this method when authenticated, then
 * redirect user to /auth/{provider}/link.
 * 
 * 'provider' can be:
 * - oidc
 */
export interface BeginExternalLoginLink {
}

/**
 * Begins enrollment flow for Passkey 2FA.
 * Response: [BeginPasskeyEnrollmentResponse]
 */
export interface BeginPasskeyEnrollment {
}

/**
 * Starts enrollment flow for TOTP 2FA auth support.
 * Response: [BeginTotpEnrollmentResponse]
 * 
 * This generates an otpauth URI for the user. User must confirm
 * by providing a valid 6 digit code for the URI to [ConfirmTotpEnrollment].
 */
export interface BeginTotpEnrollment {
}

/** Response for [BeginTotpEnrollment]. */
export interface BeginTotpEnrollmentResponse {
	/** TOTP enrollment URI for manual addition to password manager. */
	uri: string;
	/** Base64 encoded PNG embeddable in HTML to display uri QR code. */
	png: string;
}

/**
 * Confirm a single use 2fa pending token + time-dependent user totp code for a jwt.
 * Response: [CompletePasskeyLoginResponse].
 */
export interface CompletePasskeyLogin {
	credential: PublicKeyCredential;
}

/**
 * Confirm a single use 2fa pending token + time-dependent user totp code for a jwt.
 * Response: [CompleteTotpLoginResponse].
 */
export interface CompleteTotpLogin {
	/** The time dependent totp code for user. */
	code: string;
}

/**
 * Confirm enrollment flow for Passkey 2FA.
 * Response: [NoData]
 */
export interface ConfirmPasskeyEnrollment {
	credential: RegisterPublicKeyCredential;
}

/**
 * Confirm enrollment flow for TOTP 2FA auth support
 * Response: [ConfirmTotpEnrollmentResponse]
 */
export interface ConfirmTotpEnrollment {
	code: string;
}

/** Response for [ConfirmTotpEnrollment]. */
export interface ConfirmTotpEnrollmentResponse {
	recovery_codes: string[];
}

/**
 * Retrieve a JWT after completing third party login flows.
 * Response: [ExchangeForJwtResponse].
 */
export interface ExchangeForJwt {
}

/**
 * See the available options
 * users have to login, eg. local and external providers.
 * Response: [GetLoginOptionsResponse].
 */
export interface GetLoginOptions {
}

/** The response for [GetLoginOptions]. */
export interface GetLoginOptionsResponse {
	/** Whether Local login is enabled. */
	local: boolean;
	/** Whether OIDC login is enabled. */
	oidc: boolean;
	/** Whether Github login is enabled. */
	github: boolean;
	/** Whether Google login is enabled. */
	google: boolean;
	/** Whether user registration (Sign Up) has been disabled */
	registration_disabled: boolean;
}

/**
 * Login as a local user. Will fail if the users credentials don't match
 * any local user.
 */
export interface LoginLocalUser {
	/** The user's username */
	username: string;
	/** The user's password */
	password: string;
}

/**
 * Sign up a new local user account.
 * Response: [SignUpLocalUserResponse].
 */
export interface SignUpLocalUser {
	/** The username for the new user. */
	username: string;
	/**
	 * The password for the new user.
	 * This cannot be retreived later.
	 */
	password: string;
}

/**
 * Unenrolls user in Passkey 2FA.
 * Response: [NoData]
 */
export interface UnenrollPasskey {
}

/**
 * Unenrolls user in TOTP 2FA.
 * Response: [UnenrollTotpResponse]
 */
export interface UnenrollTotp {
}

/** The available login providers */
export enum LoginProvider {
	Local = "Local",
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

/** Unlink a login. Response: [NoData]. */
export interface UnlinkLogin {
	/**
	 * 'provider' can be:
	 * - Local
	 * - Oidc
	 */
	provider: LoginProvider;
}

/**
 * Update the calling user's password.
 * Response: [NoData].
 */
export interface UpdatePassword {
	password: string;
}

/**
 * Update the calling user's username.
 * Response: [NoData].
 */
export interface UpdateUsername {
	username: string;
}

/** The available external login providers */
export enum ExternalLoginProvider {
	Oidc = "Oidc",
	Github = "Github",
	Google = "Google",
}

export type LoginRequest = 
	| { type: "GetLoginOptions", params: GetLoginOptions }
	| { type: "ExchangeForJwt", params: ExchangeForJwt }
	| { type: "SignUpLocalUser", params: SignUpLocalUser }
	| { type: "LoginLocalUser", params: LoginLocalUser }
	| { type: "CompletePasskeyLogin", params: CompletePasskeyLogin }
	| { type: "CompleteTotpLogin", params: CompleteTotpLogin };

export type ManageRequest = 
	| { type: "UpdateUsername", params: UpdateUsername }
	| { type: "UpdatePassword", params: UpdatePassword }
	| { type: "BeginExternalLoginLink", params: BeginExternalLoginLink }
	| { type: "UnlinkLogin", params: UnlinkLogin }
	| { type: "BeginPasskeyEnrollment", params: BeginPasskeyEnrollment }
	| { type: "ConfirmPasskeyEnrollment", params: ConfirmPasskeyEnrollment }
	| { type: "UnenrollPasskey", params: UnenrollPasskey }
	| { type: "BeginTotpEnrollment", params: BeginTotpEnrollment }
	| { type: "ConfirmTotpEnrollment", params: ConfirmTotpEnrollment }
	| { type: "UnenrollTotp", params: UnenrollTotp };

/** JSON containing either an authentication token or the required 2fa auth check. */
export type UserIdOrTwoFactor = 
	| { type: "UserId", data: string }
	| { type: "Passkey", data: RequestChallengeResponse }
	| { type: "Totp", data: {
}};

