/*
 Generated by typeshare 1.13.4
*/

/** Where the key in use comes from. */
export const SupporterKeySource = {
	/** No key: the topbar shows "Become a supporter". */
	None: "None",
	/** The app's config (`supporter_key`), while no key is stored. */
	Config: "Config",
	/** Set with [SetSupporterKey], used over the config's. */
	Stored: "Stored",
} as const;
export type SupporterKeySource = (typeof SupporterKeySource)[keyof typeof SupporterKeySource];

/** `u64` where the typescript types have a `number`. */
export type U64 = number;

/**
 * The `t` of a payload. Serialized as its text, `individual`,
 * `organization` or `sponsor`.
 */
export const Tier = {
	Individual: "individual",
	Organization: "organization",
	Sponsor: "sponsor",
} as const;
export type Tier = (typeof Tier)[keyof typeof Tier];

/** The payload of a key, as [SupporterKeyInfo] shows it. */
export interface SupporterKeyPayload {
	/** `v`, the format version. */
	version: U64;
	/**
	 * `k`, the id of the root key which signed the key: lowercase
	 * hex.
	 */
	root_key_id: string;
	/**
	 * `i`, the id of the key: a lowercase hyphenated UUID, the form
	 * the revocation list uses.
	 */
	id: string;
	/** `a`, the app the key is for. */
	app: string;
	/** `n`, the name on the badge. */
	name: string;
	/** `t`. */
	tier: Tier;
	/** `s`, supporter since, `YYYY-MM-DD`. */
	since: string;
	/** `c`, the last release date the key covers, `YYYY-MM-DD`. */
	covers: string;
}

/**
 * What is configured, for the management UI. The key itself never
 * leaves the server.
 */
export interface SupporterKeyInfo {
	source: SupporterKeySource;
	/**
	 * Whether the app's config sets a key: what removing a stored key
	 * falls back to.
	 */
	config_key: boolean;
	/**
	 * The supporter the key in use names, decoded from its payload:
	 * what the badge shows. `None` without a key, or for a payload
	 * which does not decode ([Self::problem] says so).
	 */
	supporter?: SupporterKeyPayload;
	/**
	 * Why the key in use does not verify on the server, which then
	 * does not serve it, so it shows no badge: its payload, root
	 * signature, format version or app. `None` when the key
	 * verifies. [SetSupporterKey] refuses such a key, so this is the
	 * key of the app's config, or a stored key which verified under
	 * another release (eg. before a root key was removed). The
	 * browser verifies a served key again, also by its release date
	 * and the revocation list.
	 */
	problem?: string;
}

/** Response for [DeleteSupporterKey]: what is configured now. */
export type DeleteSupporterKeyResponse = SupporterKeyInfo;

/**
 * How the UI shows the badge of an organization's or sponsor's
 * key. Nothing in it is secret: every user's browser reads it.
 * 
 * The typescript package has the same checks (`brandingProblem`)
 * and constants.
 */
export interface SupporterBranding {
	/**
	 * The organization's icon, shown in place of the heart: an image
	 * url (`https://` or `http://`), a path on the app (`/...`), or
	 * an uploaded image as a `data:image/...;base64,` url
	 * ([ICON_MEDIA_TYPES], at most [MAX_ICON_BYTES]). `None`: the
	 * heart.
	 */
	icon?: string;
	/**
	 * The width the icon is shown at, in pixels ([MIN_ICON_SIZE] to
	 * [MAX_ICON_WIDTH]). `None`: as wide as the image is at the
	 * height it is shown at (its proportions are kept either way).
	 */
	icon_width?: number;
	/**
	 * The height the icon is shown at, in pixels ([MIN_ICON_SIZE] to
	 * [MAX_ICON_HEIGHT]). `None`: [DEFAULT_ICON_HEIGHT].
	 */
	icon_height?: number;
	/**
	 * Where a click on the badge leads, opened in a new tab: a web
	 * address (`https://` or `http://`), eg. the organization's own
	 * site. `None`: the supporter page of mogh.tech. Not used while
	 * the brand is the home button, which leads home.
	 */
	link?: string;
	/**
	 * Show the icon and the supporter's name in place of the app's
	 * home button (which still leads to `/`), instead of as a badge.
	 */
	replace_home?: boolean;
	/**
	 * Leave the supporter's name out where the brand shows (the
	 * badge, the home button): for an icon which includes the name.
	 * Only with an icon, which then stands for the name: without one
	 * the name always shows.
	 */
	hide_name?: boolean;
	/**
	 * Show the supporter's name in capital letters where the brand
	 * shows (the badge, the home button), like the apps write their
	 * own names. The name itself stays as the key has it.
	 */
	uppercase_name?: boolean;
}

/**
 * Response for [GetSupporterBranding]. The default while nothing
 * is set.
 */
export type GetSupporterBrandingResponse = SupporterBranding;

/** Response for [GetSupporterKeyInfo]. */
export type GetSupporterKeyInfoResponse = SupporterKeyInfo;

/** Response for [SetSupporterBranding]: the branding as it is kept. */
export type SetSupporterBrandingResponse = SupporterBranding;

/** Response for [SetSupporterKey]: what is configured now. */
export type SetSupporterKeyResponse = SupporterKeyInfo;

/**
 * Removes the key set with [SetSupporterKey]. The key of the app's
 * config, if any, is used again. Admin only.
 * Response: [DeleteSupporterKeyResponse].
 */
export interface DeleteSupporterKey {
}

/**
 * How the badge of an organization or sponsor is shown: what the
 * topbar reads. Nothing in it is secret. For every user. The
 * browser applies it only for a key it verified as an
 * organization's or sponsor's.
 * Response: [GetSupporterBrandingResponse].
 */
export interface GetSupporterBranding {
}

/**
 * Signs the browser's nonce with the supporter key in use, so the
 * browser can verify the key offline. The response holds nothing
 * secret, only what the badge shows. For every user.
 * Response: [GetSupporterKeyResponse].
 */
export interface GetSupporterKey {
	/**
	 * 32 bytes the browser drew, base64url without padding. Anything
	 * else is a 400 error.
	 */
	nonce: string;
}

/**
 * What is configured, for the management UI: the supporter the key
 * in use names, where the key comes from, and whether it would show
 * a badge. Never the key itself. Admin only.
 * Response: [GetSupporterKeyInfoResponse].
 */
export interface GetSupporterKeyInfo {
}

/**
 * Sets how the badge of an organization or sponsor is shown,
 * replacing what was set: kept by the app, and used from now on.
 * The branding has to be valid ([SupporterBranding::validated], a
 * 400 with the reason otherwise), and the key in use an
 * organization's or sponsor's, unless it is the default, which
 * clears it (a 400 otherwise). Admin only.
 * Response: [SetSupporterBrandingResponse].
 */
export interface SetSupporterBranding {
	branding: SupporterBranding;
}

/**
 * Sets the supporter key: kept by the app, and used from now on
 * over the key of the app's config. The key has to parse, and to
 * verify on the server: the root keys the app hardcodes, the format
 * version, the app. A key which does not is refused with a 400 and
 * the reason, and nothing changes. Admin only.
 * Response: [SetSupporterKeyResponse].
 */
export interface SetSupporterKey {
	/** The key as pasted. Whitespace in it is ignored. */
	key: string;
}

/**
 * What `GetSupporterKey` answers: everything the browser needs to
 * verify the key offline, and nothing secret. All fields are
 * base64url without padding.
 * 
 * The typescript package has it as `SignedSupporterKey` too.
 */
export interface SignedSupporterKey {
	/**
	 * `P`, the payload bytes exactly as decoded from the configured
	 * key.
	 */
	payload: string;
	/** `SP`, the root key's signature over `P || I2`. */
	payload_sig: string;
	/** `I2`, the instance public key, 32 bytes. */
	instance_public_key: string;
	/**
	 * `SN`, the instance key's signature over the nonce message
	 * ([nonce_message]).
	 */
	nonce_sig: string;
}

/** The requests of `/supporter/read`. */
export type SupporterReadRequest = 
	| { type: "GetSupporterKey", params: GetSupporterKey }
	| { type: "GetSupporterKeyInfo", params: GetSupporterKeyInfo }
	| { type: "GetSupporterBranding", params: GetSupporterBranding };

/** The requests of `/supporter/write`. */
export type SupporterWriteRequest = 
	| { type: "SetSupporterKey", params: SetSupporterKey }
	| { type: "DeleteSupporterKey", params: DeleteSupporterKey }
	| { type: "SetSupporterBranding", params: SetSupporterBranding };

